### ISSUE TITLE
Cannot Install Node-Julia

### ISSUE THREAD

**Issue by parth9615** [waTeim/node-julia#23]
I tried installing node-julia and i get this error message. Does anyone know how to fix this issue. I am running version 3.6 of npm and version 0.3.12 of Julia
<img width="1280" alt="screen shot 2016-02-01 at 11 17 48 am" src="https://cloud.githubusercontent.com/assets/5083033/12723180/5c76af88-c8d6-11e5-9f21-f3fd92a9336f.png">

**Comment by waTeim** [comment]
On OS/X, there are two things that influence what the include directory is.  First if **julia** can be detected by finding it using the *shell PATH*, then that's used (you can try using `which julia`).  And if that is not successful, then **julia** is searched for in **Applications**.  If neither one is successful then there will be an error like this one.

Thus, this could result from not being able to detect the julia install directory.  There is a script in the tools subdirectory of the node-julia install directory called `nj_config.py` that is used during installtion to determine the right value and if it is not working properly, then running it manually and noting the output can help.  Can you run the following command in the node-julia install directory?  

    python tools/nj_config.py osx base

Also the compile options used by **node-gyp** will reveal the `-I` option, and that will show where the include path is assumed to be.  If these values do not correspond to the actual value, then that explains the error.  You can install verbosely and that will reveal that compile options,  Try using this:

    npm --verbose install node-julia

**Comment by parth9615** [comment]
Running the `python tools/nj_config.py osx base` resulted in no output for me.
When i run `npm --verbose install node-julia`. These are the errors i get.

<img width="1280" alt="screen shot 2016-02-04 at 11 21 07 am" src="https://cloud.githubusercontent.com/assets/5083033/12821441/7afb9d94-cb31-11e5-980f-cb171d3ee1ef.png">

**Comment by waTeim** [comment]
This is likely the basis of the problem then as the install can not determine the location of julia.

`Running the python tools/nj_config.py osx base resulted in no output for me.
When i run npm --verbose install node-julia. These are the errors i get.`

what is the result of the command

    which julia

Where do you have julia installed?

As for your error above; strange about the circular dependency have you cloned node-julia and then npm install node-julia inside it?  

If that's the case instead simply do

    npm --verbose install

or

    node-gyp rebuild --verbose

Also if possible could you submit the relevant as text, screenshots are great for context, but they're not cut-pasteable and not searchable.

**Comment by parth9615** [comment]
The result of `which julia` results in nothing for me.
I do have julia installed, and can run julia the terminal. 
When i run `node-gyp rebuild --verbose`. The result i get is `node-gyp: command not found`
and when i run `npm --verbose install` .This is the error i get
<img width="1280" alt="screen shot 2016-02-05 at 11 23 43 am" src="https://cloud.githubusercontent.com/assets/5083033/12852015/ef8458bc-cbfa-11e5-8828-d790abad3ac2.png">

**Comment by waTeim** [comment]
Ok, though apparently node-gyp comes packaged with npm in such a way that it can be invoked automatically upon `npm install`; it can't be invoked on the command line, so can you install node-gyp globally (this is optional)?

    sudo npm -g install node-gyp

However, I'm wondering at where you have julia installed.  I don't think you can actually run it from the terminal because `which julia` would return something instead of nothing.  Instead I'm guessing you're launching julia-terminal (the command line version) via the dock or perhaps spotlight, it uses a terminal window to display the command line.

When julia can't be found via the *PATH* variable which is the case here then it falls back to searching through Applications, and if it's not there then will not be able to find it.  There's an easy remedy for you, and a test I need to perform.  Asuming it's installed in Applications, then try the following

    export PATH=$PATH:/Applications/Julia-0.3.12.app/Contents/Resources/julia/bin

and re-run npm install

**Comment by qvdgeer** [comment]
I had the same error as parth using julia 0.4.3 under OSX. Changing the path as suggested above worked thanks.

**Comment by parth9615** [comment]
Thank the path worked for me as well

**Comment by audacyDevOps** [comment]
Hi, I love the idea of node integration with julia. I'm trying to install node-julia on CentOS 7 and encounter similar issues as above. I installed Julia successfully earlier. Need help here.

**Issues**
1. Julia was installed (I executed yum install julia after defining a julia.repo) under /usr/bin/julia but npm does not find it.
2.  $PATH shows /usr/bin/julia but npm complains it can't find julia
3. I also ran sudo npm install -g node-gyp, and repeat the previous node-julia installation. same errors.
4. I add a dependency pointing to "node-julia": "git://github.com/waTeim/node-julia.git" as in the readme.md but same errors.

any pointer? thanks

Details...
```
audacy@33cd9f566fa0 node-julia]$ sudo npm install node-julia
...
  CXX(target) Release/obj.target/nj/src/nj-v10.o
  SOLINK_MODULE(target) Release/obj.target/nj.node
/bin/ld: cannot find -ljulia
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/nj.node] Error 1
make: Leaving directory `/opt/julia/node-julia/node_modules/node-julia/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-327.4.4.el7.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/julia/node-julia/node_modules/node-julia
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

```

More Details...
```
[audacy@33cd9f566fa0 node-julia]$ which julia
/usr/bin/julia
[audacy@33cd9f566fa0 node-julia]$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.3 (2016-01-12 21:37 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-redhat-linux

[audacy@33cd9f566fa0 node-julia]$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin:/usr/bin/julia:.
```

**Comment by waTeim** [comment]
Hmm ok Centos.  When it comes to Linux, the packaging can differ from Ubuntu to Centos, to whatever, but I think those are the main two for which specialized packaging exists.  The trick is to identify where the Julia library is, which usually can be inferred from where Julia the binary is installed, but it looks like Centos is different.

There is a script I wrote to assist with this and it located in the Julia share directory, where that gets installed by yum I'm not sure.  But if you can find it, run it with the --ldflags optiion.  Here's how it's installed on my machine for example (it will be different for you):

    /usr/local/julia/share/julia/julia-config.jl --ldflags
    -L/usr/local/julia-12e127fe92/lib/julia

If that works for you, what I think I should do it copy that script wholesale into this project and then it will be guaranteed that so long as Julia is available from the command line, the right arguments to node-gyp will always be determinable.

I believe that will fix accessing *libjulia*.  However, I saw also that you want to use Julia 0.4 (makes sense), and also node 0.10 because of the use of ` Release/obj.target/nj/src/nj-v10.o`.  That is a problem see [the Readme](https://github.com/waTeim/node-julia#limitations) and also [libuv issues](https://node-julia.readme.io/docs/use-of-libuv) as well as [1.2.3 release notes](https://node-julia.readme.io/docs/version-123-release-notes).  The problem is incompatible use of libuv by node and Julia.  Node 10 is quite old but Centos still distributes it.  If you can upgrade to any other newer version of node (0.12, iojs, 4.2, 5.x) do so.  it's pretty straightforward to do so especially when using Linux.

Something like


    npm -g install npm
    npm -g install n
    n 4.2

followed up by `yum remove` *whatever*  The aftermath of all of this is node will be in /usr/local instead and will be managed by *npm* and *n* rather than yum.  And it will the current LTS version of node.

**Comment by audacyDevOps** [comment]
I don't have any lucks after upgrading node.js to v0.12 using my Julia v0.4.3. I find my Julia path on my CentOS 7 under /usr/lib64/julia, and I add to my $PATH. These don't help. 

The error message suggests me to contact node-julia author. Could you help?

Details below...
**Julia path under CentOS7**
```
[root@641a84c84b98 julia]# /usr/share/julia/julia-config.jl --ldflags
-L/usr/lib64/julia
[root@641a84c84b98 julia]# ls -al /usr/lib64/julia
total 53476
drwxr-xr-x.  2 root root     4096 Feb 23 21:33 .
dr-xr-xr-x. 40 root root    36864 Feb 23 23:51 ..
-rwxr-xr-x.  1 root root   214912 Jan 13 11:13 libRmath-julia.so
lrwxrwxrwx.  1 root root       25 Feb 23 21:33 libarpack.so -> /usr/lib64/libarpack.so.2
-rwxr-xr-x.  1 root root    16696 Jan 13 11:13 libccalltest.so
```

**Upgrade NodeJS to v0.12 on CentOS**
Remove current NodeJS v0.10 first (yum remove nodejs), and then download nodejs v0.12 rpm.
```
[root@641a84c84b98 julia]# wget https://rpm.nodesource.com/pub_0.12/el/7/x86_64/nodejs-0.12.9-1nodesource.el7.centos.x86_64.rpm
--2016-02-24 00:21:56--  https://rpm.nodesource.com/pub_0.12/el/7/x86_64/nodejs-0.12.9-1nodesource.el7.centos.x86_64.rpm
Resolving rpm.nodesource.com (rpm.nodesource.com)... 162.243.142.34
Connecting to rpm.nodesource.com (rpm.nodesource.com)|162.243.142.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
```
Install with yum installer:
```
[root@641a84c84b98 julia]# yum install ./nodejs-0.12.9-1nodesource.el7.centos.x86_64.rpm 
Loaded plugins: fastestmirror, ovl
Examining ./nodejs-0.12.9-1nodesource.el7.centos.x86_64.rpm: nodejs-0.12.9-1nodesource.el7.centos.x86_64
Marking ./nodejs-0.12.9-1nodesource.el7.centos.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 0:0.12.9-1nodesource.el7.centos will be installed
--> Finished Dependency Resolution

Dependencies Resolved

[root@641a84c84b98 julia]# node --version
v0.12.9
```
**Install node-gyp (dependency first):**

```
[root@641a84c84b98 julia]# npm install -g node-gyp
/usr/bin/node-gyp -> /usr/lib/node_modules/node-gyp/bin/node-gyp.js
```
**verify $PATH includes Julia**
```
root@641a84c84b98 julia]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib64/julia::/usr/lib64/julia:.
[root@641a84c84b98 julia]# 
```

**then install node-julia:**
```
[root@641a84c84b98 julia]# npm install -g node-julia
/
> node-julia@1.2.3 install /usr/lib/node_modules/node-julia
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/node-julia/build'
  CXX(target) Release/obj.target/nj/src/Alloc.o
  CXX(target) Release/obj.target/nj/src/Call.o
  CXX(target) Release/obj.target/nj/src/Exception.o
  CXX(target) Release/obj.target/nj/src/Expr.o
  CXX(target) Release/obj.target/nj/src/Convert.o
  CXX(target) Release/obj.target/nj/src/Immediate.o
  CXX(target) Release/obj.target/nj/src/Import.o
  CXX(target) Release/obj.target/nj/src/JMain.o
  CXX(target) Release/obj.target/nj/src/JuliaExecEnv.o
  CXX(target) Release/obj.target/nj/src/JuAlloc.o
  CXX(target) Release/obj.target/nj/src/JuliaHandle.o
  CXX(target) Release/obj.target/nj/src/Kernel.o
  CXX(target) Release/obj.target/nj/src/NAlloc.o
  CXX(target) Release/obj.target/nj/src/NativeArray.o
  CXX(target) Release/obj.target/nj/src/Script.o
  CXX(target) Release/obj.target/nj/src/Trampoline.o
  CXX(target) Release/obj.target/nj/src/Type.o
  CXX(target) Release/obj.target/nj/src/Types.o
  CXX(target) Release/obj.target/nj/src/Value.o
  CXX(target) Release/obj.target/nj/src/Values.o
  CXX(target) Release/obj.target/nj/src/debug.o
  CXX(target) Release/obj.target/nj/src/error.o
  CXX(target) Release/obj.target/nj/src/lvalue.o
  CXX(target) Release/obj.target/nj/src/request.o
  CXX(target) Release/obj.target/nj/src/rvalue.o
  CXX(target) Release/obj.target/nj/src/util.o
  CXX(target) Release/obj.target/nj/src/JSAlloc.o
  CXX(target) Release/obj.target/nj/src/Callback-v11.o
  CXX(target) Release/obj.target/nj/src/JRef-v11.o
  CXX(target) Release/obj.target/nj/src/ScriptEncapsulated-v11.o
  CXX(target) Release/obj.target/nj/src/dispatch-v11.o
  CXX(target) Release/obj.target/nj/src/nj-v11.o
  SOLINK_MODULE(target) Release/obj.target/nj.node
/usr/bin/ld: cannot find -ljulia
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/nj.node] Error 1
make: Leaving directory `/usr/lib/node_modules/node-julia/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Linux 3.10.0-327.4.5.el7.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/node-julia
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.10.0-327.4.5.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "node-julia"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! node-julia@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-julia@1.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-julia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-julia
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/julia/npm-debug.log
```

**Comment by waTeim** [comment]
Great info, much thanks for that. So switching to node 12 helped, because now nj-v11 is being used (`CXX(target) Release/obj.target/nj/src/nj-v11.o`) that's good, and yea it still fails because *libjulia* can not be found, the reason is contained in the following lines in the binding.gyp file

        "conditions":
        [
          [ "gcc=='4.6'", { "std":"c++0x" } , { "std":"c++11" } ],
          [ "OS=='linux' and juliaBase=='/usr'",
            {
              "juliaLib":"/usr/lib/x86_64-linux-gnu/julia",
              "JULIA_LIB":"/usr/lib/x86_64-linux-gnu/julia",
              "juliaInclude":"/usr/include/julia"
            },


Changing the lines

              "juliaLib":"/usr/lib/x86_64-linux-gnu/julia",
              "JULIA_LIB":"/usr/lib/x86_64-linux-gnu/julia",


to

              "juliaLib":"/usr/lib64/julia",
              "JULIA_LIB":"/usr/lib64/julia",


Should resolve the -ljulia problem, but that's not the solution, it's just a simple hack if you can do that; it can serve as a workaround until I have a fix.

**Comment by waTeim** [comment]
can you attempt to install the latest from master

    npm install https://github.com/waTeim/node-julia.git

**Comment by audacyDevOps** [comment]
Thanks for feedback. It works for me now.

For the benefits of other developers, let me summarize the steps how I install and deploy node-julia successfully on CentOS 7:
1. Install Julia docker container with Node.js on CentOS7
(Remark - There are a few tricks. Do "yum install cmake" and add Julia repository "nalimilan-julia" from Julia official site. Their Website instructions are not very clear how to add this repository. Watch for incompatibility between Node.js and Julia).

2. Install Node.js v0.12. Node.js official distribution for CentOS or Redhat is v0.10 which is not compatible with Julia v0.4.x++. I use an unofficial rpm package for v0.12. This is tricky for CentOS.
3. Find Julia installation path.  CentOS7 rpm installed Julia under /usr/bin/julia but this is not the path. I finally use "find" to locate Julia distribution under /usr/lib64.
4. For your node.js package, install node-gyp dependency (e.g. npm install -g node-gyp).
5. Modify the file binding.gyp from node-gyp package as follows:

Original file:

```
vi /root/.npm/node-julia/1.2.3/package/binding.gyp
        "conditions":
        [
          [ "gcc=='4.6'", { "std":"c++0x" } , { "std":"c++11" } ],
          [ "OS=='linux' and juliaBase=='/usr'",
            {
              "juliaLib":"/usr/lib/x86_64-linux-gnu/julia",
              "JULIA_LIB":"/usr/lib/x86_64-linux-gnu/julia",
              "juliaInclude":"/usr/include/julia"
            },
            {
              "juliaLib":"<(juliaBase)/lib/julia",
              "JULIA_LIB":"<!(python tools/nj_config.py <(OS) julia_lib_define)",
              "juliaInclude":"<(juliaBase)/include/julia"
            }
          ],
```

Changes made:
```
          "conditions":
          [
            [ "OS=='linux'", { "gcc":"<!(gcc --version 2>&1 | head -1 | sed -e 's/^.*(.*) \(.*\)\..*$/\\1/')" } , { "gcc":"" } ]
          ],
          "juliaBase":"<!(python tools/nj_config.py <(OS) base)"
        },
        "version":"<!(python tools/nj_config.py <(OS) version)",
        "NJ_LIB":"<!(python tools/nj_config.py <(OS) nj_lib_define)",
        "juliaBin":"<(juliaBase)/bin",
        "V8MAJOR":"<!(node tools/nodev.js major)",
        "V8MINOR":"<!(node tools/nodev.js minor)",
        "V8PATCH":"<!(node tools/nodev.js patch)",
        "conditions":
        [
          [ "gcc=='4.6'", { "std":"c++0x" } , { "std":"c++11" } ],
          [ "OS=='linux' and juliaBase=='/usr'",
            {
              "juliaLib":"/usr/lib64/julia",
              "JULIA_LIB":"/usr/lib64/julia",
            },
            {
              "juliaLib":"<(juliaBase)/lib/julia",
              "JULIA_LIB":"<!(python tools/nj_config.py <(OS) julia_lib_define)",
              "juliaInclude":"<(juliaBase)/include/julia"
            }
          ],
```
Please note that I did not change the second section (should I change (juliaBase)/lib/julia to (juliaBase/lib64/julia)

```
       "juliaLib":"<(juliaBase)/lib/julia",
              "JULIA_LIB":"<!(python tools/nj_config.py <(OS) julia_lib_define)",
              "juliaInclude":"<(juliaBase)/include/julia"
```

6. Install node-julia
`%npm install https://github.com/waTeim/node-julia.git`

7. Verify if node-julia works
Re-use the sample file from https://github.com/waTeim/node-julia, e.g.

Create a node.js file called testme.js with the following contents:
```
julia = require('node-julia');

var a = julia.eval('[ 1 2 3 ; 3 4 1; 8 2 9]');
var b = julia.eval("[1 1 1]'");
var c = julia.exec('\\',a,b);

console.log('Solution: ' + c[0][0] + 'x + ' + c[1][0] + 'y + ' + c[2][0] + 'z');
```

Execute by "node testme.js". It should return 
```
Solution: -0.1463414634146341x + 0.3170731707317073y + 0.17073170731707316z
```

8. Next step - need to test REST API with node-julia and express.js (not done yet)

**Comment by Giarcr0b** [comment]
Hi, I'm trying to install node-Julia on an Ubuntu 16.04 server and run into similar problems to the above.

Julia was installed successfully but node-Julia returns the following errors...
Any help would be appreciated.

**Errors**

```
ubuntu@ip-172-31-32-176:~$ sudo npm install node-julia
\
> node-julia@1.2.3 install /home/ubuntu/node_modules/node-julia
> node-gyp rebuild

make: Entering directory '/home/ubuntu/node_modules/node-julia/build'
  CXX(target) Release/obj.target/nj/src/Alloc.o
  CXX(target) Release/obj.target/nj/src/Call.o
  CXX(target) Release/obj.target/nj/src/Exception.o
  CXX(target) Release/obj.target/nj/src/Expr.o
  CXX(target) Release/obj.target/nj/src/Convert.o
  CXX(target) Release/obj.target/nj/src/Immediate.o
  CXX(target) Release/obj.target/nj/src/Import.o
../src/Import.cpp: In member function â€˜virtual nj::Result nj::Import::eval(std::vector<std::shared_ptr<nj::Value> >&, int64_t)â€™:
../src/Import.cpp:39:38: error: â€˜jl_is_functionâ€™ was not declared in this scope
          if(val && jl_is_function(val)) filteredNames.push_back(*s);
                                      ^
nj.target.mk:151: recipe for target 'Release/obj.target/nj/src/Import.o' failed
make: *** [Release/obj.target/nj/src/Import.o] Error 1
make: Leaving directory '/home/ubuntu/node_modules/node-julia/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.4.0-53-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/node_modules/node-julia
gyp ERR! node -v v4.7.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-julia"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! node-julia@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-julia@1.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-julia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-julia
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-julia
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log
```
Other info..

```
ubuntu@ip-172-31-32-176:~$ which julia
/usr/bin/julia
ubuntu@ip-172-31-32-176:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-linux-gnu

julia> 
ubuntu@ip-172-31-32-176:~$ echo $PATH
/home/ubuntu/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

```
Thanks.
