### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by rand5** [waTeim/node-julia#30]
When I run `npm install node-julia --save`, I get the following error. On Windows 7
Any help is greatly appreciated.

![image](https://cloud.githubusercontent.com/assets/17629404/15332630/5e7f0684-1c34-11e6-929f-23dfc72f1535.png)

**Comment by awang94** [comment]
I'm now getting this error, on a Windows 10 machine. It's a new machine that has fresh installs of node.js, Python 2.7, Julia, and Visual Studio 2015 Community.

**Comment by muditdham** [comment]
I am facing the same build error on windows 10, 
node v6.3.0
npm 4.1.2
julia 0.5.0

ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mudit.dham\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
